name: dockerhub-workflow

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@master
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      -
        name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push tag latest
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile_alpine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:latest
      -
        name: Build and push tag alpine
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile_alpine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:alpine
      -
        name: Build and push tag alpine-8
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile_alpine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:alpine-8
          build-args: PHP_VERSION=83
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@main
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm
